FROM maven:3.8.5-openjdk-17

MAINTAINER Thibaut MOUTON <thibautmouton22@gmail.com>

RUN mkdir -p "/product/backend" && \
    mkdir uploads

WORKDIR /product/backend

COPY backend ./

RUN mvn clean install

CMD ["mvn", "spring-boot:run","-Dspring-boot.run.profiles=dev"]
