version: "3.9"
services:
  db:
    image: "mysql:8.0.29"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fastlitemessage
      MYSQL_ROOT_PASSWORD: password
  back:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-back
    ports:
      - "9090:9090"
    depends_on:
      - "db"
  web:
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "3000:3000"