export const INIT_WS_TOKEN = "INIT_WS_TOKEN";

export const INIT_WS_CONNECTION = "INIT_WS_CONNECTION";

export const SET_WS_GROUPS = "SET_WS_GROUPS";

export const WS_CHECK_CONNECTED = "WS_CHECK_CONNECTED";

export const CURRENT_ACTIVE_GROUP = "CURRENT_ACTIVE_GROUP";

export const GRANT_USER_ADMIN = "GRANT_USER_ADMIN";

export const FETCH_GROUP_MESSAGES = "FETCH_GROUP_MESSAGES";

export const SET_CHAT_HISTORY = "SET_CHAT_HISTORY";

export const SET_ACTIVE_GROUP = "SET_ACTIVE_GROUP";

export const SET_ALL_MESSAGES_FETCHED = "SET_ALL_MESSAGES_FETCHED";

export const HANDLE_RTC_ACTIONS = "HANDLE_RTC_ACTIONS";

export const HANDLE_RTC_OFFER = "HANDLE_RTC_OFFER";

export const HANDLE_RTC_ANSWER = "HANDLE_RTC_ANSWER";

export const SET_RTC_OFFER = "SET_RTC_OFFER";

export const SET_RTC_ANSWER = "SET_RTC_OFFER";

export const HANDLE_RTC_CANDIDATE = "HANDLE_RTC_CANDIDATE";

export const SEND_TO_SERVER = "SEND_TO_SERVER";

export const SEND_GROUP_MESSAGE = "SEND_GROUP_MESSAGE";

export const ADD_CHAT_HISTORY = "ADD_CHAT_HISTORY";

export const UNSUBSCRIBE_ALL = "UNSUBSCRIBE_ALL";

export const MARK_MESSAGE_AS_SEEN = "MARK_MESSAGE_AS_SEEN";
