export enum RtcActionEnum {
  INIT_ROOM = "INIT_ROOM",

  LEAVE_ROOM = "LEAVE_ROOM",

  JOIN_ROOM = "JOIN_ROOM",

  SEND_OFFER = "SEND_OFFER",

  SEND_ANSWER = "SEND_ANSWER",

  ICE_CANDIDATE = "ICE_CANDIDATE",

  CHECK_EXISTING_CALL = "CHECK_EXISTING_CALL",

  CALL_IN_PROGRESS = "CALL_IN_PROGRESS",

  NO_CALL_IN_PROGRESS = "NO_CALL_IN_PROGRESS",
}
