export enum TransportActionEnum {
  FETCH_GROUP_MESSAGES = "FETCH_GROUP_MESSAGES",
  SEND_GROUP_MESSAGE = "SEND_GROUP_MESSAGE",
  NOTIFICATION_MESSAGE = "NOTIFICATION_MESSAGE",
  GRANT_USER_ADMIN = "GRANT_USER_ADMIN",
  ADD_CHAT_HISTORY = "ADD_CHAT_HISTORY",
  MARK_MESSAGE_AS_SEEN = "MARK_MESSAGE_AS_SEEN",
  LEAVE_GROUP = "LEAVE_GROUP",
  CALL_INCOMING = "CALL_INCOMING",
  END_CALL = "END_CALL",
  CHECK_EXISTING_CALL = "CHECK_EXISTING_CALL",
}
