export enum TransportActionEnum {
    INIT_USER_DATA = "INIT_USER_DATA",
    CONNECT = "CONNECT",
    FETCH_GROUP_MESSAGES = "FETCH_GROUP_MESSAGES",
    SEND_GROUP_MESSAGE = "SEND_GROUP_MESSAGE",
    NOTIFICATION_MESSAGE = "NOTIFICATION_MESSAGE",
    GRANT_USER_ADMIN = "GRANT_USER_ADMIN"
}
