package com.mercure.utils;

public enum TransportActionEnum {
    SEND_GROUP_MESSAGE,
    FETCH_GROUP_MESSAGES,
    CALL_INCOMING,
    ADD_CHAT_HISTORY,
    NOTIFICATION_MESSAGE,
    GRANT_USER_ADMIN,
    MARK_MESSAGE_AS_SEEN,
    LEAVE_GROUP,
    CHECK_EXISTING_CALL,
    CALL_IN_PROGRESS,
    END_CALL,
    NO_CALL_IN_PROGRESS,
}
