name: back

on: push
#  push:
#    paths: ["backend/**"]

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - id: "auth"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v3

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . -f gateway/Dockerfile  --platform linux/amd64 --tag ${{ secrets.REGISTRY_AREA }}/${{ secrets.STORAGE_SERVICE_NAME }}:1.0.0
        working-directory: "backend"

      - name: Push image
        run: |-
          docker push ${{ secrets.REGISTRY_AREA }}
