name: front

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install dependencies
        run: npm --prefix ./frontend-web install
      - name: test front
        id: test
        run: npm --prefix ./frontend-web run test
     
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install
        run: npm --prefix ./frontend-web ci
      - name: build
        run: npm --prefix ./frontend-web run build
      - name: cache build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          retention-days: 2
          
  login:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_HOST }}
          username: _json_key
          password: ${{ secrets.DOCKER_REGISTRY_SA }}

  push:
    needs: login
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:frontend-web"
          push: true
          tags: ${{ secrets.SERVICE_NAME }}:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy artifact
        run: |
          gcloud auth activate-service-account ${{ secrets.CLOUD_RUN_SA }} --key-file=${{ secrets.CLOUD_RUN_SA_KEY }}
          gcloud run deploy ${{ secrets.SERVICE_NAME }} --service-account=${{ secrets.CLOUD_RUN_SA }} --allow-unauthenticated --region=${{ secrets.REGION }} --project=${{ secrets.REGION }} --port=80 --image=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}/${{ secrets.SERVICE_NAME }}:latest
          gcloud beta run services add-iam-policy-binding --region=${{ secrets.REGION }} --member=allUsers --role=roles/run.invoker ${{ secrets.SERVICE_NAME }} --project=${{ secrets.PROJECT_ID}}
