name: build-front

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: build
        run: npm --prefix frontend-web run build
